import { z } from 'zod';
import { createTRPCRouter, publicProcedure } from '../trpc';
import { stripe } from '@/lib/Stripe';

const paymentInput = z
    .object({
        item: z.object({
            name: z.string(),
            price: z.number(),
            oldPrice: z.number().nullable(),
            id: z.number(),
            mainImage: z.object({ url: z.string() }).nullable(),
        }),
        size: z.object({ name: z.string(), id: z.number().optional() }),
        colour: z.object({ name: z.string(), id: z.number().optional() }),
        quantity: z.number(),
    })
    .array()
    .optional();

export const paymentRouter = createTRPCRouter({
    makePayment: publicProcedure.input(paymentInput).mutation(async ({ ctx, input: items }) => {
        if (items == null || items.length === 0) return null;
        const session = await stripe.checkout.sessions.create({
            line_items: items?.map(({ item, size, colour, quantity }) => {
                return {
                    price_data: {
                        currency: 'gbp',
                        product_data: {
                            name: item.name,
                            metadata: {
                                size: size.name,
                                colour: colour.name,
                            },
                        },
                        unit_amount: item.price * 100,
                    },
                    quantity,
                };
            }),
            mode: 'payment',
            success_url: `${process.env.NEXT_PUBLIC_DOMAIN_URL}/basket?order=success`,
            cancel_url: `${process.env.NEXT_PUBLIC_DOMAIN_URL}/basket`,
            payment_intent_data: {
                metadata: {
                    items: JSON.stringify(
                        items.map(item => {
                            return { itemId: item.item.id, price: item.item.price, size: item.size.name, colour: item.colour.name, quantity: item.quantity };
                        })
                    ),
                },
            },
            shipping_address_collection: {
                allowed_countries: [
                    'AC',
                    'AD',
                    'AE',
                    'AF',
                    'AG',
                    'AI',
                    'AL',
                    'AM',
                    'AO',
                    'AQ',
                    'AR',
                    'AT',
                    'AU',
                    'AW',
                    'AX',
                    'AZ',
                    'BA',
                    'BB',
                    'BD',
                    'BE',
                    'BF',
                    'BG',
                    'BH',
                    'BI',
                    'BJ',
                    'BL',
                    'BM',
                    'BN',
                    'BO',
                    'BQ',
                    'BR',
                    'BS',
                    'BT',
                    'BV',
                    'BW',
                    'BY',
                    'BZ',
                    'CA',
                    'CD',
                    'CF',
                    'CG',
                    'CH',
                    'CI',
                    'CK',
                    'CL',
                    'CM',
                    'CN',
                    'CO',
                    'CR',
                    'CV',
                    'CW',
                    'CY',
                    'CZ',
                    'DE',
                    'DJ',
                    'DK',
                    'DM',
                    'DO',
                    'DZ',
                    'EC',
                    'EE',
                    'EG',
                    'EH',
                    'ER',
                    'ES',
                    'ET',
                    'FI',
                    'FJ',
                    'FK',
                    'FO',
                    'FR',
                    'GA',
                    'GB',
                    'GD',
                    'GE',
                    'GF',
                    'GG',
                    'GH',
                    'GI',
                    'GL',
                    'GM',
                    'GN',
                    'GP',
                    'GQ',
                    'GR',
                    'GS',
                    'GT',
                    'GU',
                    'GW',
                    'GY',
                    'HK',
                    'HN',
                    'HR',
                    'HT',
                    'HU',
                    'ID',
                    'IE',
                    'IL',
                    'IM',
                    'IN',
                    'IO',
                    'IQ',
                    'IS',
                    'IT',
                    'JE',
                    'JM',
                    'JO',
                    'JP',
                    'KE',
                    'KG',
                    'KH',
                    'KI',
                    'KM',
                    'KN',
                    'KR',
                    'KW',
                    'KY',
                    'KZ',
                    'LA',
                    'LB',
                    'LC',
                    'LI',
                    'LK',
                    'LR',
                    'LS',
                    'LT',
                    'LU',
                    'LV',
                    'LY',
                    'MA',
                    'MC',
                    'MD',
                    'ME',
                    'MF',
                    'MG',
                    'MK',
                    'ML',
                    'MM',
                    'MN',
                    'MO',
                    'MQ',
                    'MR',
                    'MS',
                    'MT',
                    'MU',
                    'MV',
                    'MW',
                    'MX',
                    'MY',
                    'MZ',
                    'NA',
                    'NC',
                    'NE',
                    'NG',
                    'NI',
                    'NL',
                    'NO',
                    'NP',
                    'NR',
                    'NU',
                    'NZ',
                    'OM',
                    'PA',
                    'PE',
                    'PF',
                    'PG',
                    'PH',
                    'PK',
                    'PL',
                    'PM',
                    'PN',
                    'PR',
                    'PS',
                    'PT',
                    'PY',
                    'QA',
                    'RE',
                    'RO',
                    'RS',
                    'RU',
                    'RW',
                    'SA',
                    'SB',
                    'SC',
                    'SE',
                    'SG',
                    'SH',
                    'SI',
                    'SJ',
                    'SK',
                    'SL',
                    'SM',
                    'SN',
                    'SO',
                    'SR',
                    'SS',
                    'ST',
                    'SV',
                    'SX',
                    'SZ',
                    'TA',
                    'TC',
                    'TD',
                    'TF',
                    'TG',
                    'TH',
                    'TJ',
                    'TK',
                    'TL',
                    'TM',
                    'TN',
                    'TO',
                    'TR',
                    'TT',
                    'TV',
                    'TW',
                    'TZ',
                    'UA',
                    'UG',
                    'US',
                    'UY',
                    'UZ',
                    'VA',
                    'VC',
                    'VE',
                    'VG',
                    'VN',
                    'VU',
                    'WF',
                    'WS',
                    'XK',
                    'YE',
                    'YT',
                    'ZA',
                    'ZM',
                    'ZW',
                    'ZZ',
                ],
            },
            shipping_options: [
                {
                    shipping_rate_data: {
                        type: 'fixed_amount',
                        fixed_amount: {
                            amount: 0,
                            currency: 'gbp',
                        },
                        display_name: 'Free shipping',
                        delivery_estimate: {
                            minimum: {
                                unit: 'business_day',
                                value: 4,
                            },
                            maximum: {
                                unit: 'business_day',
                                value: 5,
                            },
                        },
                    },
                },
                {
                    shipping_rate_data: {
                        type: 'fixed_amount',
                        fixed_amount: {
                            amount: 1000,
                            currency: 'gbp',
                        },
                        display_name: 'Next day delivery',
                        delivery_estimate: {
                            minimum: {
                                unit: 'business_day',
                                value: 1,
                            },
                            maximum: {
                                unit: 'business_day',
                                value: 1,
                            },
                        },
                    },
                },
            ],
        });
        return session.url;
    }),
});
